name: suggests

on:
  schedule:
    - cron: '0 03 * * 5' # every Friday at 1am
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            geocompr/geocompr
            ghcr.io/geocompx/suggests
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,
            type=raw,value={{date 'YYYY-MM-DD'}},prefix=date_
            type=raw,value=latest
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push # Or similar name
        uses: docker/build-push-action@v6
        with:
          context: suggests
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }} # Adjust if meta step is different
          labels: ${{ steps.meta.outputs.labels }} # Adjust if meta step is different
          secrets: |
            "GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}"
